#!/usr/bin/env python3
"""Resolve the manifest branch and every floating project revision to commits.

Writes two files that the build consumes and that are committed to git:

  <lock>       KEY=value lines: manifest URL/branch/file/commit, plus one
               "PROJECT <path> <commit>" line per project the build asserts on
               (every project declared directly in the top-level manifest and
               every project whose manifest revision is a branch name).
  <pins.xml>   A repo local manifest with <extend-project revision=...> for the
               floating projects, so `repo sync` checks out exactly the recorded
               commits instead of whatever the branch points at today.

Only the stdlib is used; network access is `git ls-remote` and HTTPS fetches of
the manifest XML at the resolved commit.

Usage:
  write-lock.py [--debug] [--check]
    --debug   use pico/emu-35-rom-debug.xml -> revisions-debug.lock / pins-debug.xml
    --check   do not write; exit 1 (with a diff) if the files would change
"""
import argparse
import difflib
import os
import re
import subprocess
import sys
import urllib.request
import xml.etree.ElementTree as ET

MANIFEST_URL = os.environ.get("MANIFEST_URL", "https://github.com/komastudios/PICO-Emulator-manifest.git")
MANIFEST_BRANCH = os.environ.get("MANIFEST_BRANCH", "pico-linux")
SHA_RE = re.compile(r"^[0-9a-f]{40}$")


def ls_remote(url, ref):
    out = subprocess.run(["git", "ls-remote", url, ref], check=True, capture_output=True, text=True).stdout
    for line in out.splitlines():
        sha, name = line.split("\t", 1)
        if name == ref:
            return sha
    sys.exit(f"error: {ref} not found in {url}")


def raw_url(manifest_url, rev, path):
    m = re.match(r"https://github\.com/([^/]+)/([^/]+?)(?:\.git)?$", manifest_url)
    if not m:
        sys.exit(f"error: only GitHub manifest URLs are supported, got {manifest_url}")
    return f"https://raw.githubusercontent.com/{m.group(1)}/{m.group(2)}/{rev}/{path}"


def fetch(url):
    with urllib.request.urlopen(url, timeout=30) as r:
        return r.read()


def load_manifest(manifest_url, rev, path, depth=0):
    """Return (remotes, default, projects, top_level_paths) with includes flattened."""
    root = ET.fromstring(fetch(raw_url(manifest_url, rev, path)))
    remotes, default, projects, removed, top = {}, {}, [], set(), []
    for el in root:
        if el.tag == "include":
            # repo resolves <include name> relative to the manifest repository root
            r, d, p, _ = load_manifest(manifest_url, rev, el.get("name"), depth + 1)
            remotes.update(r)
            default = {**d, **default}
            projects.extend(p)
        elif el.tag == "remote":
            remotes[el.get("name")] = el.get("fetch")
        elif el.tag == "default":
            default.update(el.attrib)
        elif el.tag == "remove-project":
            removed.add(el.get("name"))
        elif el.tag == "project":
            projects.append(dict(el.attrib))
            if depth == 0:
                top.append(el.get("path", el.get("name")))
    projects = [p for p in projects if p["name"] not in removed]
    return remotes, default, projects, top


def project_url(remotes, default, p):
    fetch_base = remotes[p.get("remote", default.get("remote"))]
    return fetch_base.rstrip("/") + "/" + p["name"]


def build(debug):
    manifest_file = "pico/emu-35-rom-debug.xml" if debug else "pico/emu-35-rom.xml"
    manifest_rev = ls_remote(MANIFEST_URL, f"refs/heads/{MANIFEST_BRANCH}")
    remotes, default, projects, top = load_manifest(MANIFEST_URL, manifest_rev, manifest_file)

    pinned, floating = [], []
    for p in projects:
        path = p.get("path", p["name"])
        rev = p.get("revision") or default.get("revision")
        if SHA_RE.match(rev or ""):
            if path in top:
                pinned.append((path, rev))
            continue
        ref = rev if rev.startswith("refs/") else f"refs/heads/{rev}"
        sha = ls_remote(project_url(remotes, default, p), ref)
        floating.append((path, p["name"], rev, sha))

    lock = ["# Generated by scripts/write-lock.py; update with `task lock`. Do not edit by hand.",
            f"MANIFEST_URL={MANIFEST_URL}",
            f"MANIFEST_BRANCH={MANIFEST_BRANCH}",
            f"MANIFEST_FILE={manifest_file}",
            f"MANIFEST_REV={manifest_rev}"]
    entries = sorted(pinned + [(path, sha) for path, _, _, sha in floating])
    lock += [f"PROJECT {path} {sha}" for path, sha in entries]

    pins = ['<?xml version="1.0" encoding="UTF-8"?>',
            "<!-- Generated by scripts/write-lock.py; update with `task lock`. Do not edit by hand.",
            f"     Pins projects that the manifest leaves on a branch, as of manifest {manifest_rev[:12]}. -->",
            "<manifest>"]
    for path, name, branch, sha in sorted(floating):
        pins.append(f'  <extend-project name="{name}" path="{path}" revision="{sha}" /><!-- was {branch} -->')
    pins.append("</manifest>")
    return "\n".join(lock) + "\n", "\n".join(pins) + "\n"


def write_if_changed(path, content, check):
    old = open(path).read() if os.path.exists(path) else ""
    if old == content:
        print(f"unchanged: {path}")
        return False
    if check:
        sys.stdout.writelines(difflib.unified_diff(old.splitlines(True), content.splitlines(True), path, path + " (upstream)"))
        return True
    tmp = path + ".tmp"
    with open(tmp, "w") as f:
        f.write(content)
    os.replace(tmp, path)
    print(f"updated:   {path}")
    return True


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--debug", action="store_true")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    suffix = "-debug" if a.debug else ""
    lock, pins = build(a.debug)
    changed = write_if_changed(os.path.join(root, f"revisions{suffix}.lock"), lock, a.check)
    changed |= write_if_changed(os.path.join(root, "manifests", f"pins{suffix}.xml"), pins, a.check)
    if a.check and changed:
        print("lock is behind upstream; run `task lock` to update", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
